Revert "Remove color from Makefile"
This reverts commit d01ae31bc0810027a1fd6430acd6b4410fb172ef.

diff --git a/lib/ssm/Makefile b/lib/ssm/Makefile
--- a/lib/ssm/Makefile
+++ b/lib/ssm/Makefile
@@ -23,20 +23,24 @@ OBJECTS = $(patsubst src/%.c, build/%.o, $(SOURCES))
 EXAMPLES = $(wildcard examples/*.c)
 EXAMPLEEXES = $(patsubst examples/%.c, build/%, $(EXAMPLES))
 
+RED = \e[31m
+GREEN = \e[32m
+RESET_COLOR = \e[0m
+
 ARFLAGS = -cr
 
 all : test-examples test_main
 
 test_main : build/test_main
-	./build/test_main > build/test_main.out || echo "TEST_MAIN FAILED"
+	./build/test_main > build/test_main.out || echo "${RED}TEST_MAIN FAILED${RESET_COLOR}"
 	@(diff test/test_main.out build/test_main.out && \
-	echo "TEST_MAIN PASSED") || \
-	echo "TEST_MAIN OUTPUT DIFFERS"
+	echo "${GREEN}TEST_MAIN PASSED${RESET_COLOR}") || \
+	echo "${RED}TEST_MAIN OUTPUT DIFFERS${RESET_COLOR}"
 test-examples : examples
 	./runexamples > build/examples.out
 	@(diff test/examples.out build/examples.out && \
-	echo "EXAMPLES PASSED") || \
-	echo "EXAMPLE OUTPUT DIFFERS"
+	echo "${GREEN}EXAMPLES PASSED${RESET_COLOR}") || \
+	echo "${RED}EXAMPLE OUTPUT DIFFERS${RESET_COLOR}"
 
 build/test_main : test/test_main.c build/libssm.a
 	$(CC) $(CFLAGS) -o $@ test/test_main.c -Lbuild -lssm
